language: python
python:
  - "3.6"      # current default Python on Travis CI
  - "3.7"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - python -m pip install --upgrade setuptools wheel
  - python setup.py sdist bdist_wheel
  - python -m pip install --upgrade twine
# command to run tests
script:
  - python -m twine upload dist/* -u $PYPINAME -p $PYPIPW