language: python
python:
  - "3.6"      # current default Python on Travis CI
  - "3.7"
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - pytest tests
# Deploy on pypi
#deploy:
#  provider: pypi
#  user: xxxxx     # pypi username
#  password: xxxxxx  # pypi password
#  on:
#    tags: true
#    branch: main