language: python
matrix:
    include:
     - os: linux
       python: 3.6
       env: IS_DEPLOYED=0
     - os: linux
       python: 3.7
       env: IS_DEPLOYED=0
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - python -m pytest tests
# Deploy on pypi
deploy:
  provider: pypi
  user: $PYPINAME     # pypi username
  password: $PYPIPW  # pypi password
  on:
#    tags: true
    branch: main
    condition: $IS_DEPLOYED == 1